model:
  input_size: 10
  hidden_size: 64
  state_size: 32          # New parameter
  num_state_layers: 2     # New parameter
  dropout_rate: 0.2
  weight_decay: 0.01
  model_type: "state_space_bssnn"  # Use "bssnn" for original model, "state_space_bssnn"
  early_stopping_patience: 10
  early_stopping_min_delta: 0.0001

training:
  num_epochs: 100
  batch_size: 32
  learning_rate: 0.001
  display_metrics:
    - accuracy
    - f1_score
    - auc_roc
    - calibration_error

data:
  input_path: 
  feature_columns:
    - feature1
    - feature2
    - feature3
  target_column: target
  validation:
    test_size: 0.2  # Final test set size
    val_size: 0.2   # Validation set size for each fold
    n_folds: 5      # Number of cross-validation folds
    stratify: true  # Whether to use stratified splits
  random_state: 42
  
  # Synthetic data parameters (used if input_path is null)
  synthetic_samples: 100
  synthetic_features: 10
  synthetic_informative: 6
  synthetic_redundant: 4

explainability:
  enabled: true
  background_samples: 100
  max_val_samples: 100
  feature_names:
    # - Feature 1
    # - Feature 2
    # - Feature 3

output:
  base_dir: "results"
  model_dir: "models"
  explanations_dir: "explanations"
  logs_dir: "logs"
  save_model: false