model:
  input_size: null
  hidden_size: 128
  state_size: 64          # New parameter
  num_state_layers: 2     # New parameter
  dropout_rate: 0.3
  weight_decay: 0.001
  model_type: "state_space_bssnn"  # Use "bssnn" for original model, "state_space_bssnn"
  early_stopping_patience: 30
  early_stopping_min_delta: 0.001

training:
  num_epochs: 200
  batch_size: 64
  learning_rate: 0.001
  display_metrics:
    - accuracy
    - f1_score
    - auc_roc
    - calibration_error

data:
  input_path: "C:\\Users\\Emanuele\\Documents\\Progetti Python\\BSSNN\\data\\raw\\T01.csv"
  feature_columns: []  # Leave empty for auto-detection
  target_column: "Label"
  exclude_columns:  # New field for columns to exclude
    - "Id"
    - "Segment"
  validation:
    test_size: 0.2
    val_size: 0.2
    n_folds: 5
    stratify: true
  random_state: 42
  
  # Synthetic data parameters (used if input_path is null)
  synthetic_samples: 1000
  synthetic_features: null
  synthetic_informative: null
  synthetic_redundant: null

explainability:
  enabled: true
  background_samples: 100
  max_val_samples: 100
  feature_names: []  # Will be automatically populated

output:
  base_dir: "results"
  model_dir: "models"
  explanations_dir: "explanations"
  logs_dir: "logs"
  save_model: true